worldName: example-world-name
serverName: example-server-name
password: password 
valheimplus: "false"

resources: {}

storage:
  kind: hostvol
  hostvol:
    path: /data/valheim

networking:
  serviceType: LoadBalancer

nodeSelector: {}

securityContext: {}
podSecurityContext: {}
